print("Mi Primer Programa...!!!!!")
print("****Anita Hurtado****")
print("Septimo - Sistemas - Semipresencial - B")
print("Operaciones Basicas")
print("Exponenciacion")
print(2 ** 3)
print("Multiplicacion")
print(2 * 3)
print("Division")
print(6 / 3)
print("Division Entera")
print(6 // 3)
print("Operadores Resto %")
print(14 % 4)
